// <auto-generated />
namespace Community_Trust.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedShowSubmissionsView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedShowSubmissionsView));
        
        string IMigrationMetadata.Id
        {
            get { return "201711152147572_addedShowSubmissionsView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
