// <auto-generated />
namespace Community_Trust.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addSubmissionDTO_Mapper : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSubmissionDTO_Mapper));
        
        string IMigrationMetadata.Id
        {
            get { return "201711222237508_addSubmissionDTO_Mapper"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
